import { createAction } from '@reduxjs/toolkit';
import { User, LoginRequest } from '../../models/user.model';

// Action Types with createAction
export const LOGIN_REQUEST = createAction<LoginRequest>('LOGIN_REQUEST');
export const LOGIN_SUCCESS = createAction<{ token: string }>('LOGIN_SUCCESS');
export const LOGIN_FAILURE = createAction<{ error: any }>('LOGIN_FAILURE');
export const LOGOUT = createAction('LOGOUT');
export const LOAD_USER_REQUEST = createAction('LOAD_USER_REQUEST');
export const LOAD_USER_SUCCESS = createAction<{ user: User }>('LOAD_USER_SUCCESS');
export const LOAD_USER_FAILURE = createAction<{ error: any }>('LOAD_USER_FAILURE');

// Action Creators are automatically generated by createAction
export const loginRequest = LOGIN_REQUEST;
export const loginSuccess = LOGIN_SUCCESS;
export const loginFailure = LOGIN_FAILURE;
export const logout = LOGOUT;
export const loadUserRequest = LOAD_USER_REQUEST;
export const loadUserSuccess = LOAD_USER_SUCCESS;
export const loadUserFailure = LOAD_USER_FAILURE;

// Union type for all auth actions (for compatibility with existing code)
export type AuthActionTypes =
  | ReturnType<typeof loginRequest>
  | ReturnType<typeof loginSuccess>
  | ReturnType<typeof loginFailure>
  | ReturnType<typeof logout>
  | ReturnType<typeof loadUserRequest>
  | ReturnType<typeof loadUserSuccess>
  | ReturnType<typeof loadUserFailure>;
