import { createAction } from '@reduxjs/toolkit';
import { Todo } from '../../models/todo.model';

// Action Types with createAction
export const LOAD_TODOS = createAction<{ todos: Todo[] }>('LOAD_TODOS');
export const ADD_TODO = createAction<{ title: string }>('ADD_TODO');
export const TOGGLE_TODO = createAction<{ id: number }>('TOGGLE_TODO');
export const DELETE_TODO = createAction<{ id: number }>('DELETE_TODO');

// Action Creators are automatically generated by createAction
export const loadTodos = (todos: Todo[]) => LOAD_TODOS({ todos });
export const addTodo = (title: string) => ADD_TODO({ title });
export const toggleTodo = (id: number) => TOGGLE_TODO({ id });
export const deleteTodo = (id: number) => DELETE_TODO({ id });

// Union type for all todo actions (for compatibility with existing code)
export type TodoActionTypes =
  | ReturnType<typeof loadTodos>
  | ReturnType<typeof addTodo>
  | ReturnType<typeof toggleTodo>
  | ReturnType<typeof deleteTodo>;
